#%RAML 1.0 DataType


type: object
properties:
  title:
    type: string
    required: true
  author:
    type: string
    required: true
  thumbnail:
    type: string
    required: true    
  selftext:
    type: string
    required: true    
  ups:
    type: number
    required: true    
  downs:
    type: number
    required: true    