#%RAML 1.0
title: feed-mgmt-api
version: v1
mediaType: [application/json,application/xml ]
protocols: [HTTP,HTTPS]

types:
  feed-data: !include datatype/feed_datatype.raml

traits:
  x-clientid-enforcement:
    headers:
      client_id:
        type: string
        example: "8732687442846"
      client_secret:
        type: string
        example: "8732687442846"        



/feeds:
  
  is: [ x-clientid-enforcement]
  get:
   description: get the record in SF for last modified data limit 100
   responses:
    200:
      body:
        application/json:
          example: !include example/feed-response.json
  post:
    description: create the record in SF
    body:
      application/json:
        type: feed-data
        example: !include example/feed-response.json
    responses:
      200:
        body:
          application/json:
            example: "Record is created successfully"

  /{id}:
    get:
      description: Get record for the particular Id
      responses:
        200:
          body:
            application/json:
              example: !include example/feed-response.json

    put:
      description: update the record in SF
      body:
        application/json:
          type: feed-data
          example: !include example/feed-response.json
      responses:
        200:
          body:
            application/json:
              example: "successfully updated the record"  

    delete:
      description: delete record for the particular Id
      responses:
        200:
          body:
            application/json:
              example: "Deleted the record successfully"
              
              


